Add support for openssl code-signing verification
AUTHORS.rst:
Add Anton Hvornum to list of authors.

CHANGELOG.rst:
Add changelog entry for new feature.

README.rst:
Add openssl to list of requirements for CMS verification.

docs/README.bootparams:
Add documentation for the `cms_verify` kernel parameter.

hooks/archiso:
Add `_verify_cms_signature()` to verify openssl CMS signatures.
Change `archiso_mount_handler()` to also deal with openssl CMS signature verification.

hooks/archiso_pxe_http:
Change `archiso_pxe_http_mount_handler()` to retrieve cms based signatures from the remote host if `cms_verify=y` is
provided as kernel parameter.

install/archiso:
Change `build()` to install the openssl binary as it is required for openssl CMS signature verification and to add the
codesigning certificate and certificate authority to the build root.

diff --git a/hooks/archiso b/hooks/archiso
--- a/hooks/archiso
+++ b/hooks/archiso
@@ -134,6 +134,38 @@ _verify_signature() {
     return ${_status}
 }
 
+_verify_cms_signature() {
+    # Note: There is an "issue" with openssl.
+    # Which requires emailProtection in extended key usage on the code signing certificate.
+    # See: https://github.com/openssl/openssl/issues/17134
+    local _status
+    local cms_sigfile="${1}"
+    local bootfile="${2}"
+    local certfile="/codesign.crt"
+    local cafile="/codesign_CA.crt"
+
+    if [ ! -e "$cafile" ]; then
+        cafile="$certfile"
+    fi
+
+    cd "/run/archiso/bootmnt/${archisobasedir}/${arch}" || exit 1
+    # "-purpose any" can be removed once the issue mentioned above is fixed.
+    openssl cms \
+        -verify \
+        -binary \
+        -noattr \
+        -purpose any \
+        -in "${cms_sigfile}" \
+        -content "${bootfile}" \
+        -inform DER \
+        -out /dev/null \
+        -certfile "$certfile" \
+        -CAfile "$cafile"
+    _status=$?
+    cd -- "${OLDPWD}" || exit 1
+    return ${_status}
+}
+
 run_hook() {
     [ -z "${arch}" ] && arch="$(uname -m)"
     [ -z "${copytoram_size}" ] && copytoram_size="75%"
@@ -167,10 +199,22 @@ run_hook() {
 # args: /path/to/newroot
 archiso_mount_handler() {
     local newroot="${1}"
-    local sigfile fs_img
+    local sigfile cms_sigfile fs_img
 
     if ! mountpoint -q "/run/archiso/bootmnt"; then
         _mnt_dev "${archisodevice}" "/run/archiso/bootmnt" "-r" "defaults"
+    fi
+
+    # We need this block at the top for early failure
+    # but also to be able to give the fs_img to CMS verification.
+    # (sha512sum files contain the image, CMS files does not)
+    if [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.sfs" ]; then
+        fs_img="/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.sfs"
+    elif [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.erofs" ]; then
+        fs_img="/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.erofs"
+    else
+        echo "ERROR: no root file system image found"
+        launch_interactive_shell
     fi
 
     # shellcheck disable=SC2154
@@ -194,12 +238,9 @@ archiso_mount_handler() {
     # shellcheck disable=SC2154
     # defined via initcpio's parse_cmdline()
     if [ "${verify}" = "y" ]; then
-        if [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.sfs.sig" ]; then
-            sigfile="airootfs.sfs.sig"
-        elif [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.erofs.sig" ]; then
-            sigfile="airootfs.erofs.sig"
-        fi
-        if [ -n "${sigfile}" ]; then
+        if [ -f "${fs_img}.sig" ]; then
+            sigfile="${fs_img##*/}.sig"
+
             msg ":: Signature verification requested, please wait..."
             if _verify_signature "${sigfile}"; then
                 msg "Signature is OK, continue booting."
@@ -209,6 +250,25 @@ archiso_mount_handler() {
             fi
         else
             echo "ERROR: verify=y option specified but GPG signature not found in ${archisobasedir}/${arch}/"
+            launch_interactive_shell
+        fi
+    fi
+
+    # shellcheck disable=SC2154
+    # defined via initcpio's parse_cmdline()
+    if [ "${cms_verify}" = "y" ]; then
+        if [ -f "${fs_img}.cms.sig" ]; then
+            cms_sigfile="${fs_img##*/}.cms.sig"
+
+            msg ":: Signature verification requested, please wait..."
+            if _verify_cms_signature "${cms_sigfile}" "${fs_img}"; then
+                msg "Signature is OK, continue booting."
+            else
+                echo "ERROR: one or more files are corrupted"
+                launch_interactive_shell
+            fi
+        else
+            echo "ERROR: cms_verify=y option specified but CMS signature not found in ${archisobasedir}/${arch}/"
             launch_interactive_shell
         fi
     fi
@@ -230,14 +290,6 @@ archiso_mount_handler() {
     mkdir -p "/run/archiso/cowspace/${cow_directory}"
     chmod 0700 "/run/archiso/cowspace/${cow_directory}"
 
-    if [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.sfs" ]; then
-        fs_img="/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.sfs"
-    elif [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.erofs" ]; then
-        fs_img="/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.erofs"
-    else
-        echo "ERROR: no root file system image found"
-        launch_interactive_shell
-    fi
     _mnt_fs "${fs_img}" "/run/archiso/airootfs"
     if [ -f "/run/archiso/airootfs/airootfs.img" ]; then
         _mnt_dmsnapshot "/run/archiso/airootfs/airootfs.img" "${newroot}" "/"
