hooks/archiso: use resolve_device() instead of poll_device()
Unlike `poll_device`, `resolve_device` supports using tags (e.g. `UUID=`,
`LABEL=`, `PARTUUID=`, `PARTLABEL=`) to specify a device.
This is a lot more _prettier_ than using the `/dev/disk/by-*/*` symlinks.

Since `mount` supports these tags, they can be passed to it as is.

Implements #10

diff --git a/hooks/archiso b/hooks/archiso
--- a/hooks/archiso
+++ b/hooks/archiso
@@ -95,16 +95,22 @@ _mnt_dev() {
     local mnt="${2}"
     local flg="${3}"
     local opts="${4}"
+    local resolved_dev
 
     msg ":: Mounting '${dev}' to '${mnt}'"
 
-    while ! poll_device "${dev}" 30; do
-        echo "ERROR: '${dev}' device did not show up after 30 seconds..."
+    while ! resolved_dev="$(rootdelay="${rootdelay:-30}" resolve_device "${dev}")"; do
+        echo "ERROR: '${dev}' device did not show up after ${rootdelay:-30} seconds..."
         echo "   Falling back to interactive prompt"
         echo "   You can try to fix the problem manually, log out when you are finished"
         launch_interactive_shell
     done
 
+    # If the tag is supported by mount, pass it as is. Otherwise, use the resolved device path.
+    case "${dev}" in
+        'UUID='* | 'LABEL='* | 'PARTUUID='* | 'PARTLABEL='*) : ;;
+        *) dev="${resolved_dev}" ;;
+    esac
     if mount --mkdir -o "${opts}" "${flg}" "${dev}" "${mnt}"; then
         msg ":: Device '${dev}' mounted successfully."
     else
