Do not include the gpg binary unless ARCHISO_GNUPG_FD is set durring build
Handle the condition when signature verification is requested but the
`gpg` binary is not available.

Since now there is OpenSSL CMS based root file system image verification,
GPG based verification should be made optional.
`mkarchiso` currently requires running as root, which complicates signing
with user's GPG keys. E.g. running it with `sudo` may require chowning
the TTY and passing the `GNUPGHOME` environment variable.
While the cause of this annoyance is `mkarchiso`, `gpg` doesn't make the
process easy.
OpenSSL CMS based signing has none of these issues.

diff --git a/hooks/archiso b/hooks/archiso
--- a/hooks/archiso
+++ b/hooks/archiso
@@ -241,6 +241,11 @@ archiso_mount_handler() {
     # shellcheck disable=SC2154
     # defined via initcpio's parse_cmdline()
     if [ "${verify}" = "y" ]; then
+        if ! command -v gpg >/dev/null 2>&1; then
+            echo 'ERROR: verify=y option specified but the gpg binary is not available in initramfs'
+            launch_interactive_shell
+        fi
+
         if [ -f "${fs_img}.sig" ]; then
             sigfile="${fs_img##*/}.sig"
 
